/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.milaifontanals.vista;



import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.milaifontanals.model.Artista;
import org.milaifontanals.model.Canso;
import org.milaifontanals.model.Estil;
import org.milaifontanals.model.Llista;
import org.milaifontanals.model.Producte;
import org.milaifontanals.model.Tipus_Producte;
import org.milaifontanals.persistencia.CapaPersistencia;
import org.milaifontanals.persistencia.GestorBDEmpresaException;
/**
 *
 * @author isard
 */
public class Contingut_Llista extends javax.swing.JDialog {

    /**
     * Creates new form Contingut_Llista
     */
    
    
    private CapaPersistencia cBD = null;
    List<Estil> est = new ArrayList<Estil>();
    List<Artista> art = new ArrayList<Artista>();
    List<Producte> alb_cont = new ArrayList<Producte>();
    List<Producte> alb_taula = new ArrayList<Producte>();

    ButtonGroup bG = new ButtonGroup();
    Producte prod= null;
    
    int j;
    double durada=0;
    int hores;
    int minuts;
    int segons;
    double total;
    
    
    
    public Contingut_Llista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Estil_combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Titol_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Cerca_BT = new javax.swing.JButton();
        Netejar_BT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Llista_resultat = new javax.swing.JTable();
        Afegir_BT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Taula_Contingut = new javax.swing.JTable();
        Eliminar_BT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        Cancelar_BT = new javax.swing.JButton();
        Crear_BT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir cançons/àlbum a la llista"));

        jLabel5.setText("Estil: ");

        jLabel6.setText("Títol: ");

        Cerca_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-search-32.png"))); // NOI18N
        Cerca_BT.setText("Cerca");
        Cerca_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerca_BTActionPerformed(evt);
            }
        });

        Netejar_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-erase-32.png"))); // NOI18N
        Netejar_BT.setText("Neteja Filtre");
        Netejar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Netejar_BTActionPerformed(evt);
            }
        });

        Llista_resultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Llista_resultat);

        Afegir_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-add-file-16.png"))); // NOI18N
        Afegir_BT.setText("Afageix Contingut");
        Afegir_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Afegir_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(45, 45, 45)
                        .addComponent(Estil_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Titol_field, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Netejar_BT)
                    .addComponent(Afegir_BT)
                    .addComponent(Cerca_BT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Estil_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Titol_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cerca_BT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Netejar_BT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Afegir_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contingut actual de la llista"));

        Taula_Contingut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Taula_Contingut);

        Eliminar_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-trash-16.png"))); // NOI18N
        Eliminar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_BTActionPerformed(evt);
            }
        });

        jLabel8.setText("Eliminar contingut seleccionat:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Eliminar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addContainerGap(20, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        Cancelar_BT.setText("Cancelar");
        Cancelar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_BTActionPerformed(evt);
            }
        });

        Crear_BT.setText("Editar");
        Crear_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar_BT)
                    .addComponent(Crear_BT))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Crear_BT)
                .addGap(18, 18, 18)
                .addComponent(Cancelar_BT)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cerca_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerca_BTActionPerformed
        List<Producte> filtre = new ArrayList<Producte>();

        Estil estil = new Estil (Estil_combo.getSelectedItem().toString());

        if(estil.getNom().contains("Tots")){
            estil.setNom("");
        }

        try {
            filtre = cBD.getProductesLlista(estil, Titol_field.getText());
            ContingutTaulaFiltre(filtre);
        } catch (GestorBDEmpresaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Cerca_BTActionPerformed

    private void Netejar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Netejar_BTActionPerformed
        DadesTaula();
        Titol_field.setText("");
        Estil_combo.setSelectedIndex(0);

    }//GEN-LAST:event_Netejar_BTActionPerformed

    private void Afegir_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Afegir_BTActionPerformed
        j = Llista_resultat.getSelectedRow();

        if(j==-1){
            JOptionPane.showMessageDialog(this, "Hem de seleccionar un Autor per la canço que volm crear");
        }else{

            String nom = alb_taula.get(j).getTitol();

            boolean trobat=false;
            for(int i =0; i<alb_cont.size();i++){
                if(alb_cont.get(i).getTitol().equals(nom)){
                    trobat = true;
                }
            }

            if(trobat==true){
                JOptionPane.showMessageDialog(this, "Aquesta canço ja esta incluida en el àlbum");
            }else if(trobat==false){
              
                alb_cont.add(alb_taula.get(j));
                ContingutTaulaCont(alb_cont);
            }

        }
    }//GEN-LAST:event_Afegir_BTActionPerformed

    private void Eliminar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_BTActionPerformed
        int x= Taula_Contingut.getSelectedRow();
        if(x==-1){
            JOptionPane.showMessageDialog(this, "Hem de seleccionar una canso que volem eliminar");
        }else{
           
            alb_cont.remove(x);
            ContingutTaulaCont(alb_cont);
        }

    }//GEN-LAST:event_Eliminar_BTActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        try {
            est=cBD.getEstils();   
            Estil_combo.addItem("Tots");
           
            for(int i =0; i<est.size();i++){
                Estil_combo.addItem(est.get(i).getNom());
                 Estil_combo.addItem(est.get(i).getNom());
            }
            
            
            art=cBD.TaulaInterpret();
            alb_cont = cBD.ContingutLlista(prod);
            
            DadesTaula();
            ContingutTaulaCont(alb_cont);
        
        
        } catch (GestorBDEmpresaException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void Cancelar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_BTActionPerformed
       this.dispose();
    }//GEN-LAST:event_Cancelar_BTActionPerformed

    private void Crear_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_BTActionPerformed
        double durada =0;
  
    
       try {
       
       for(int i=0; i<alb_cont.size();i++){
             
            cBD.afegirContingutLlista(prod.getId(),alb_cont.get(i).getId());
               
              durada=durada +cBD.getDurada(alb_cont.get(i).getId());
          
       }
       total=durada;
       cBD.updateDuradaAlbum(durada,prod.getId());
       CalcularTemps(durada);
       
         JOptionPane.showMessageDialog(this, "Contingut modificat sense cap problema");
         JOptionPane.showMessageDialog(this, "La durada de la llista s'ha actualitzat amb la suma de la durada del seu contingut:"+hores+":"+minuts+":"+segons);
       
      } catch (GestorBDEmpresaException ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_Crear_BTActionPerformed

    public void DadesTaula() {
         try{
            
            alb_taula= cBD.Omplir_Taula_Productes_Llista();
            
            ContingutTaulaFiltre(alb_taula);
            
        }catch (GestorBDEmpresaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ContingutTaulaFiltre(List<Producte> cont) {
        Llista_resultat.removeAll();
      try{
            String columnNames []={"Títol","Estil","Tipus","Estat","Durada"};
            String data[][]= new String [cont.size()][5];
         
         
        for(int i =0; i<cont.size();i++){
                
            
                double durada = cBD.getDurada(cont.get(i).getId());
                CalcularTemps(durada);
            
            
            
                data[i][0]=cont.get(i).getTitol();
                data[i][1]=cont.get(i).getEstil().getNom();
                data[i][2]=cont.get(i).getTp().toString();
                data[i][3]=cont.get(i).isActiu();
                data[i][4]=(hores+":"+minuts+":"+segons);
            }
            
            Llista_resultat.setDefaultEditor(Object.class, null);
            Llista_resultat.setModel(new DefaultTableModel(data,columnNames));
        }catch (GestorBDEmpresaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
            
    }
    
    
     private void ContingutTaulaCont(List<Producte> cont) {
        Taula_Contingut.removeAll();
         
        try{
            
       
        String columnNames []={"Títol","Estil","Tipus","Estat","Durada"};
            String data[][]= new String [cont.size()][5];
         
         
        for(int i =0; i<cont.size();i++){
                
                 double durada = cBD.getDurada(cont.get(i).getId());
                CalcularTemps(durada);
            
            
                data[i][0]=cont.get(i).getTitol();
                data[i][1]=cont.get(i).getEstil().getNom();
                data[i][2]=cont.get(i).getTp().toString();
                data[i][3]=cont.get(i).isActiu();
                data[i][4]=(hores+":"+minuts+":"+segons);
            }
            
            Taula_Contingut.setDefaultEditor(Object.class, null);
            Taula_Contingut.setModel(new DefaultTableModel(data,columnNames));
            
         }catch (GestorBDEmpresaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }   
    }
     
      private void CalcularTemps(double durada) {
            double calcul;
            calcul= durada/60;
            hores=(int)calcul;
            calcul=calcul-hores;
            calcul=calcul*60;
            minuts=(int)calcul;
            calcul=calcul-minuts;
            calcul=calcul*60;
            segons=(int)calcul;
            
    }
    
    
    
    
    void pasarProducte(Producte pr) {
      prod=pr;
    }

    double getDuarada() {
       return total;
    }
    
 
    void setConnexio(CapaPersistencia conn) {
       cBD=conn;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contingut_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contingut_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contingut_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contingut_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Contingut_Llista dialog = new Contingut_Llista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afegir_BT;
    private javax.swing.JButton Cancelar_BT;
    private javax.swing.JButton Cerca_BT;
    private javax.swing.JButton Crear_BT;
    private javax.swing.JButton Eliminar_BT;
    private javax.swing.JComboBox<String> Estil_combo;
    private javax.swing.JTable Llista_resultat;
    private javax.swing.JButton Netejar_BT;
    private javax.swing.JTable Taula_Contingut;
    private javax.swing.JTextField Titol_field;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
