/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.milaifontanals.vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.milaifontanals.model.Artista;
import org.milaifontanals.model.Canso;
import org.milaifontanals.model.Estil;
import org.milaifontanals.model.Llista;
import org.milaifontanals.model.Producte;
import org.milaifontanals.model.Tipus_Producte;
import org.milaifontanals.persistencia.CapaPersistencia;
import org.milaifontanals.persistencia.GestorBDEmpresaException;

/**
 *
 * @author isard
 */
public class Creacio_Llista extends javax.swing.JDialog {

    private CapaPersistencia cBD = null;
    List<Estil> est = new ArrayList<Estil>();
    List<Artista> art = new ArrayList<Artista>();
    List<Producte> alb_cont = new ArrayList<Producte>();
    List<Producte> alb_taula = new ArrayList<Producte>();
    List<Producte> agafar = new ArrayList<Producte>();
    ButtonGroup bG = new ButtonGroup();
    
    int j;
    double durada=0;
    int hores;
    int minuts;
    int segons;
    /**
     * Creates new form Creacio_Llista
     */
    public Creacio_Llista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear_BT = new javax.swing.JButton();
        Cancelar_BT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Titol_field = new javax.swing.JTextField();
        Estil_combo = new javax.swing.JComboBox<>();
        Any_SP = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        Actiu_RB = new javax.swing.JRadioButton();
        Inactiu_RB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Estil_combo1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Titol_field1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Cerca_BT = new javax.swing.JButton();
        Netejar_BT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Llista_resultat = new javax.swing.JTable();
        Afegir_BT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Taula_Contingut = new javax.swing.JTable();
        Eliminar_BT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Crear_BT.setText("Crear");
        Crear_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_BTActionPerformed(evt);
            }
        });

        Cancelar_BT.setText("Cancelar");
        Cancelar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_BTActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dades producte"));

        jLabel1.setText("Títol: ");

        jLabel2.setText("Estil: ");

        jLabel3.setText("Any de creació: ");

        Any_SP.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2500, 1));

        jLabel4.setText("Estat:");

        Actiu_RB.setText("Actiu");
        Actiu_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actiu_RBActionPerformed(evt);
            }
        });

        Inactiu_RB.setText("Inactiu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Titol_field))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Estil_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Any_SP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Inactiu_RB)
                                    .addComponent(Actiu_RB))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Titol_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Estil_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Any_SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(Actiu_RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inactiu_RB)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir cançons/àlbum a la llista"));

        jLabel5.setText("Estil: ");

        jLabel6.setText("Títol: ");

        Cerca_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-search-32.png"))); // NOI18N
        Cerca_BT.setText("Cerca");
        Cerca_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerca_BTActionPerformed(evt);
            }
        });

        Netejar_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-erase-32.png"))); // NOI18N
        Netejar_BT.setText("Neteja Filtre");
        Netejar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Netejar_BTActionPerformed(evt);
            }
        });

        Llista_resultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Llista_resultat);

        Afegir_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-add-file-16.png"))); // NOI18N
        Afegir_BT.setText("Afageix Contingut");
        Afegir_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Afegir_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(45, 45, 45)
                        .addComponent(Estil_combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Titol_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Netejar_BT)
                    .addComponent(Afegir_BT)
                    .addComponent(Cerca_BT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Estil_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Titol_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Cerca_BT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(Netejar_BT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Afegir_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contingut actual de la llista"));

        Taula_Contingut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Taula_Contingut);

        Eliminar_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-trash-16.png"))); // NOI18N
        Eliminar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_BTActionPerformed(evt);
            }
        });

        jLabel8.setText("Eliminar contingut seleccionat:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Eliminar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addContainerGap(20, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar_BT)
                    .addComponent(Crear_BT)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Crear_BT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelar_BT)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_BTActionPerformed
       long id = 0;
       Tipus_Producte tp = null;
       tp = Tipus_Producte.L;
       boolean estat=true;
       
       if(Actiu_RB.isSelected()){
           estat=true;
       }else if(Inactiu_RB.isSelected()){
           estat=false;
       }
       
      Estil estil= null;
        estil=new Estil(Estil_combo.getSelectedItem().toString());
       
       
        String titol;
       titol=Titol_field.getText();
       
       if(titol.length()<1){
             JOptionPane.showMessageDialog(this, "El titol de la cançó ha de tenir com a mínim un caràcter");
       }else{
           try {
               
             cBD.afegirProducte(titol,estat,estil,tp);
            
             id = cBD.getIDProducteAfegit();
             Llista nou = new Llista(id,0);
              cBD.afegirLlista(id);
      
       for(int i=0; i<alb_cont.size();i++){
             
            cBD.afegirContingutLlista(id,alb_cont.get(i).getId());
               
              durada=cBD.getDurada(alb_cont.get(i).getId());
          
       }
       
       cBD.updateDuradaAlbum(durada,id);
       CalcularTemps(durada);
       
       
      
       
         JOptionPane.showMessageDialog(this, "Productes afegits a la Llista sense cap problema");
         JOptionPane.showMessageDialog(this, "La durada de la llista s'ha actualitzat amb la suma de la durada del seu contingut:"+hores+":"+minuts+":"+segons);
       
      } catch (GestorBDEmpresaException ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
       }
       
      
       
    }//GEN-LAST:event_Crear_BTActionPerformed

    private void Netejar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Netejar_BTActionPerformed
         DadesTaula();
        Titol_field.setText("");
        Estil_combo1.setSelectedIndex(0);
       
    }//GEN-LAST:event_Netejar_BTActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       //Carreguem el combo de estils i artisyes
        

        try {
            est=cBD.getEstils();   
            Estil_combo1.addItem("Tots");
           
            for(int i =0; i<est.size();i++){
                Estil_combo1.addItem(est.get(i).getNom());
                 Estil_combo.addItem(est.get(i).getNom());
            }
            
            
            art=cBD.TaulaInterpret();
            
            
            DadesTaula();
            ContingutTaulaCont(alb_cont);
            
             bG.add(Actiu_RB);
             bG.add(Inactiu_RB);
       
        
        
         //De base l'estat seleccionat ha de ser "actiu"
         Actiu_RB.setSelected(true);
            
            
            
        } catch (GestorBDEmpresaException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void Cerca_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerca_BTActionPerformed
      List<Producte> filtre = new ArrayList<Producte>();
      
        
        Estil estil = new Estil (Estil_combo1.getSelectedItem().toString());
        
        if(estil.getNom().contains("Tots")){
            estil.setNom("");
        }
        
        try {
            filtre = cBD.getProductesLlista(estil, Titol_field1.getText());
            ContingutTaulaFiltre(filtre);
        } catch (GestorBDEmpresaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Cerca_BTActionPerformed

    private void Afegir_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Afegir_BTActionPerformed
       j = Llista_resultat.getSelectedRow();
          
        
        
        if(j==-1){
            JOptionPane.showMessageDialog(this, "Hem de seleccionar un Autor per la canço que volm crear");
        }else{
            
            
            
            String nom = alb_taula.get(j).getTitol();
            
           boolean trobat=false;
            for(int i =0; i<alb_cont.size();i++){
                if(alb_cont.get(i).getTitol().equals(nom)){
                    trobat = true;
                }
            }
            
                if(trobat==true){
                     JOptionPane.showMessageDialog(this, "Aquesta canço ja esta incluida en el àlbum");
                }else if(trobat==false){
                    agafar.add(alb_taula.get(j));
                     alb_cont=agafar;
                       ContingutTaulaCont(alb_cont);
                }
           
           
          
            
        }
    }//GEN-LAST:event_Afegir_BTActionPerformed

    private void Eliminar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_BTActionPerformed
         int x= Taula_Contingut.getSelectedRow();
        if(x==-1){
            JOptionPane.showMessageDialog(this, "Hem de seleccionar una canso que volem eliminar");
        }else{
            agafar.remove(x);
            alb_cont = agafar;
        ContingutTaulaCont(alb_cont);
        }
       
    }//GEN-LAST:event_Eliminar_BTActionPerformed

    private void Actiu_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actiu_RBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actiu_RBActionPerformed

    private void Cancelar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_BTActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar_BTActionPerformed

    
    public void DadesTaula() {
         try{
            
            alb_taula= cBD.Omplir_Taula_Productes_Llista();
            
            ContingutTaulaFiltre(alb_taula);
            
        }catch (GestorBDEmpresaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ContingutTaulaFiltre(List<Producte> cont) {
        Llista_resultat.removeAll();
      
            String columnNames []={"Títol","Estil","Tipus","Estat"};
            String data[][]= new String [cont.size()][4];
         
         
        for(int i =0; i<cont.size();i++){
                
                data[i][0]=cont.get(i).getTitol();
                data[i][1]=cont.get(i).getEstil().getNom();
                data[i][2]=cont.get(i).getTp().toString();
                data[i][3]=cont.get(i).isActiu();
            }
            
            Llista_resultat.setDefaultEditor(Object.class, null);
            Llista_resultat.setModel(new DefaultTableModel(data,columnNames));
            
            
    }
    
    
     private void ContingutTaulaCont(List<Producte> cont) {
        Taula_Contingut.removeAll();
         String columnNames []={"Títol","Estil","Tipus","Estat"};
            String data[][]= new String [cont.size()][4];
         
         
        for(int i =0; i<cont.size();i++){
                
                data[i][0]=cont.get(i).getTitol();
                data[i][1]=cont.get(i).getEstil().getNom();
                data[i][2]=cont.get(i).getTp().toString();
                data[i][3]=cont.get(i).isActiu();
            }
            
            Taula_Contingut.setDefaultEditor(Object.class, null);
            Taula_Contingut.setModel(new DefaultTableModel(data,columnNames));
            
            
    }
     
      private void CalcularTemps(double durada) {
            double calcul;
            calcul= durada/60;
            hores=(int)calcul;
            calcul=calcul-hores;
            calcul=calcul*60;
            minuts=(int)calcul;
            calcul=calcul-minuts;
            calcul=calcul*60;
            segons=(int)calcul;
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacio_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacio_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacio_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacio_Llista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Creacio_Llista dialog = new Creacio_Llista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Actiu_RB;
    private javax.swing.JButton Afegir_BT;
    private javax.swing.JSpinner Any_SP;
    private javax.swing.JButton Cancelar_BT;
    private javax.swing.JButton Cerca_BT;
    private javax.swing.JButton Crear_BT;
    private javax.swing.JButton Eliminar_BT;
    private javax.swing.JComboBox<String> Estil_combo;
    private javax.swing.JComboBox<String> Estil_combo1;
    private javax.swing.JRadioButton Inactiu_RB;
    private javax.swing.JTable Llista_resultat;
    private javax.swing.JButton Netejar_BT;
    private javax.swing.JTable Taula_Contingut;
    private javax.swing.JTextField Titol_field;
    private javax.swing.JTextField Titol_field1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    void setConnexio(CapaPersistencia conn) {
       cBD=conn;
    }
}
