/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.milaifontanals.vista;

import java.awt.CheckboxGroup;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.milaifontanals.model.Estil;
import org.milaifontanals.model.Producte;
import org.milaifontanals.model.Tipus_Producte;
import org.milaifontanals.persistencia.CapaPersistencia;
import org.milaifontanals.persistencia.GestorBDEmpresaException;

/**
 *
 * @author isard
 */
public class Productes extends javax.swing.JDialog {

    private CapaPersistencia cBD = null;
    
     ButtonGroup bG = new ButtonGroup();
     CheckboxGroup cbg = new CheckboxGroup();
    /**
     * Creates new form Productes
     */
    public Productes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setConnexio(CapaPersistencia con){
        this.cBD=con;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ID_etiqueta = new javax.swing.JLabel();
        Titol_etiqueta = new javax.swing.JLabel();
        Estat_etiqueta = new javax.swing.JLabel();
        Tipus_etiqueta = new javax.swing.JLabel();
        ID_field = new javax.swing.JTextField();
        Titol_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Estil_combo = new javax.swing.JComboBox<>();
        Actiu_RB = new javax.swing.JRadioButton();
        Inactiu_RB = new javax.swing.JRadioButton();
        Tots_RB = new javax.swing.JRadioButton();
        Canso_CH = new javax.swing.JCheckBox();
        Album_CH = new javax.swing.JCheckBox();
        Llista_CH = new javax.swing.JCheckBox();
        Filtre_BT = new javax.swing.JToggleButton();
        Netejar_BT = new javax.swing.JToggleButton();
        Gestio_Panel = new javax.swing.JPanel();
        Afegir_BT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Editar_BT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Eliminar_BT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Informe_BT = new javax.swing.JButton();
        Informe_etiqueta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Content_BT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informació del producte/Filtre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel1.setForeground(new java.awt.Color(0, 153, 255));

        ID_etiqueta.setText("ID: ");

        Titol_etiqueta.setText("Títol: ");

        Estat_etiqueta.setText("Estat: ");

        Tipus_etiqueta.setText("Tipus: ");

        ID_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_fieldActionPerformed(evt);
            }
        });

        Titol_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Titol_fieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Estil: ");

        Estil_combo.setMaximumRowCount(100);
        Estil_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        Estil_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estil_comboActionPerformed(evt);
            }
        });

        Actiu_RB.setText("Actiu");
        Actiu_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actiu_RBActionPerformed(evt);
            }
        });

        Inactiu_RB.setText("Inactiu");
        Inactiu_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inactiu_RBActionPerformed(evt);
            }
        });

        Tots_RB.setText("Tots");
        Tots_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tots_RBActionPerformed(evt);
            }
        });

        Canso_CH.setText("Cançó");
        Canso_CH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Canso_CHActionPerformed(evt);
            }
        });

        Album_CH.setText("Àlbum");
        Album_CH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Album_CHActionPerformed(evt);
            }
        });

        Llista_CH.setText("Llista");
        Llista_CH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Llista_CHActionPerformed(evt);
            }
        });

        Filtre_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-search-32.png"))); // NOI18N
        Filtre_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre_BTActionPerformed(evt);
            }
        });

        Netejar_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-erase-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ID_etiqueta)
                            .addGap(18, 18, 18)
                            .addComponent(ID_field, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Titol_etiqueta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Titol_field))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Estat_etiqueta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Inactiu_RB)
                                .addComponent(Actiu_RB)
                                .addComponent(Tots_RB))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Estil_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Tipus_etiqueta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Album_CH)
                            .addComponent(Canso_CH)
                            .addComponent(Llista_CH)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Filtre_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Netejar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_etiqueta)
                    .addComponent(ID_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titol_etiqueta)
                    .addComponent(Titol_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estat_etiqueta)
                    .addComponent(Actiu_RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inactiu_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tots_RB)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Estil_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipus_etiqueta)
                    .addComponent(Canso_CH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Album_CH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Llista_CH)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Netejar_BT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Filtre_BT)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Gestio_Panel.setBackground(new java.awt.Color(51, 204, 255));
        Gestio_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestió de Productes"));

        Afegir_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-add-file-16.png"))); // NOI18N

        jLabel2.setText("Afegir Nou Producte");

        Editar_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-edit-16.png"))); // NOI18N

        jLabel3.setText("Editar Producte");

        Eliminar_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-trash-16.png"))); // NOI18N

        jLabel4.setText("Eliminar Producte");

        javax.swing.GroupLayout Gestio_PanelLayout = new javax.swing.GroupLayout(Gestio_Panel);
        Gestio_Panel.setLayout(Gestio_PanelLayout);
        Gestio_PanelLayout.setHorizontalGroup(
            Gestio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gestio_PanelLayout.createSequentialGroup()
                .addGroup(Gestio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addComponent(Afegir_BT)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addComponent(Editar_BT)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addComponent(Eliminar_BT)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        Gestio_PanelLayout.setVerticalGroup(
            Gestio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gestio_PanelLayout.createSequentialGroup()
                .addGroup(Gestio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Afegir_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addGroup(Gestio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Editar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGroup(Gestio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Gestio_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Gestio_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41))))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Informe del llistat"));

        Informe_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-send-job-list-32.png"))); // NOI18N

        Informe_etiqueta.setText("Generar Informe");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Informe_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Informe_etiqueta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Informe_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Informe_etiqueta)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Veure Contingut"));

        Content_BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/Imatges/icons8-show-property-32.png"))); // NOI18N

        jLabel5.setText("Veure Contingut");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Content_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Content_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultat de la Recerca"));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Gestio_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Gestio_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_fieldActionPerformed

    private void Titol_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Titol_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Titol_fieldActionPerformed

    private void Actiu_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actiu_RBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Actiu_RBActionPerformed

    private void Inactiu_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inactiu_RBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inactiu_RBActionPerformed

    private void Tots_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tots_RBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tots_RBActionPerformed

    private void Estil_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estil_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estil_comboActionPerformed

    private void Canso_CHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Canso_CHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Canso_CHActionPerformed

    private void Album_CHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Album_CHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Album_CHActionPerformed

    private void Llista_CHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Llista_CHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Llista_CHActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Afegim a un grup de botons els nostres radio buttons
        DadesTaula();
        Configurar_Butons();
        Omplir_Estils();
        
    }//GEN-LAST:event_formWindowOpened

    private void Filtre_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre_BTActionPerformed
        
        
        
    }//GEN-LAST:event_Filtre_BTActionPerformed

    
    
    
    public void Omplir_Estils(){
        List<Estil> estils = new ArrayList<Estil>();
        
        
        try {
            estils = cBD.getEstils();
            for(int i =0; i<estils.size();i++){
                Estil_combo.addItem(estils.get(i).getNom());
            }
   
        } catch (GestorBDEmpresaException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
            
          
    }
    
    
    public void Configurar_Butons(){
        
   
        bG.add(Actiu_RB);
        bG.add(Inactiu_RB);
        bG.add(Tots_RB);
        
        
         //De base l'estat seleccionat ha de ser "actiu"
         Actiu_RB.setSelected(true);
         
         //De base tots els tipus han d'estar seleccionats
         
         
         
         
         Canso_CH.setSelected(true);
         Album_CH.setSelected(true);
         Llista_CH.setSelected(true);
    }
    
    
    private void DadesTaula() {
        
        jTable1.removeAll();
        //Omplim la taula amb les reproduccions actuals
        List<Producte> rep = new ArrayList<Producte>();
        try{
            
            rep = cBD.Omplir_Taula_Productes();
            
            
            ContingutTaula(rep);
            
            
            
            
        }catch (GestorBDEmpresaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Ups, ha hagut un error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
     private void ContingutTaula(List<Producte> rep) {
         
         String columnNames []={"ID","Títol","Estil","Tipus","Estat"};
            String data[][]= new String [rep.size()][5];
         
         
        for(int i =0; i<rep.size();i++){
                
                
                data[i][0]=rep.get(i).getIdString();
                data[i][1]=rep.get(i).getTitol();
                data[i][2]=rep.get(i).getEstil().getNom();
                data[i][3]=rep.get(i).getTp();
                data[i][4]=rep.get(i).isActiu();
            }
            
            
            jTable1.setModel(new DefaultTableModel(data,columnNames));
    }
   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Productes dialog = new Productes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Actiu_RB;
    private javax.swing.JButton Afegir_BT;
    private javax.swing.JCheckBox Album_CH;
    private javax.swing.JCheckBox Canso_CH;
    private javax.swing.JButton Content_BT;
    private javax.swing.JButton Editar_BT;
    private javax.swing.JButton Eliminar_BT;
    private javax.swing.JLabel Estat_etiqueta;
    private javax.swing.JComboBox<String> Estil_combo;
    private javax.swing.JToggleButton Filtre_BT;
    private javax.swing.JPanel Gestio_Panel;
    private javax.swing.JLabel ID_etiqueta;
    private javax.swing.JTextField ID_field;
    private javax.swing.JRadioButton Inactiu_RB;
    private javax.swing.JButton Informe_BT;
    private javax.swing.JLabel Informe_etiqueta;
    private javax.swing.JCheckBox Llista_CH;
    private javax.swing.JToggleButton Netejar_BT;
    private javax.swing.JLabel Tipus_etiqueta;
    private javax.swing.JLabel Titol_etiqueta;
    private javax.swing.JTextField Titol_field;
    private javax.swing.JRadioButton Tots_RB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   

    
}
